<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>tost</AssemblyName>
    <RootNamespace>Trionine.TOST.Linux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOST.Core\TOST.Core.csproj" />
  </ItemGroup>
</Project>
