<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TOST.Desktop</AssemblyName>
    <RootNamespace>Trionine.TOST.Desktop</RootNamespace>
    <Version>2.0.0</Version>
    <ApplicationIcon Condition="$([MSBuild]::IsOSPlatform('Windows'))">..\Assets\tost.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);CS9057</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <ProjectReference Include="..\Core\TOST.Core.csproj" />
    <AvaloniaResource Include="..\Assets\TOST.png" Link="Assets\TOST.png" />
  </ItemGroup>
</Project>
